spring:
  application:
    name: chatbot-java-backend
  datasource:
    url: jdbc:postgresql://localhost:5436/chatbot
    password: postgres
    username: postgres

chatbot:
  openai:
    api:
      key: ${OPENAI_API_KEY}
    assistant:
      id: ${OPENAI_ASSISTANT_ID}